# Generated by Django 3.0.6 on 2020-05-21 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200521_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='filing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
