# Generated by Django 3.0.6 on 2020-05-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_myuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In_Pogress'), ('DONE', 'Done'), ('INVALID', 'Invalid')], default='NEW', max_length=11),
        ),
    ]
